// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnu80yk8-iDaBsChn5mzO6eCr9C8AtTdQ',
    appId: '1:1055155041163:web:9e49264ec66429b908758e',
    messagingSenderId: '1055155041163',
    projectId: 'todolist-92e3c',
    authDomain: 'todolist-92e3c.firebaseapp.com',
    storageBucket: 'todolist-92e3c.firebasestorage.app',
    measurementId: 'G-R8GR00D7NC',
    // Bắt buộc cho Realtime Database; nếu sai, copy URL tại Firebase Console → Realtime Database.
    databaseURL: 'https://todolist-92e3c-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt9Rek5GeoUB02DFZV81fA7OIpzrZ-QYo',
    appId: '1:1055155041163:android:33dc7a5004f833c508758e',
    messagingSenderId: '1055155041163',
    projectId: 'todolist-92e3c',
    storageBucket: 'todolist-92e3c.firebasestorage.app',
    databaseURL: 'https://todolist-92e3c-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrXdeylOmtE6Ez2PLaAptrP37FagqksB0',
    appId: '1:1055155041163:ios:5be9cbddde8153eb08758e',
    messagingSenderId: '1055155041163',
    projectId: 'todolist-92e3c',
    storageBucket: 'todolist-92e3c.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
    databaseURL: 'https://todolist-92e3c-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrXdeylOmtE6Ez2PLaAptrP37FagqksB0',
    appId: '1:1055155041163:ios:5be9cbddde8153eb08758e',
    messagingSenderId: '1055155041163',
    projectId: 'todolist-92e3c',
    storageBucket: 'todolist-92e3c.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
    databaseURL: 'https://todolist-92e3c-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnu80yk8-iDaBsChn5mzO6eCr9C8AtTdQ',
    appId: '1:1055155041163:web:bab04ed9be41163108758e',
    messagingSenderId: '1055155041163',
    projectId: 'todolist-92e3c',
    authDomain: 'todolist-92e3c.firebaseapp.com',
    storageBucket: 'todolist-92e3c.firebasestorage.app',
    measurementId: 'G-46PPFD6DKV',
    databaseURL: 'https://todolist-92e3c-default-rtdb.firebaseio.com',
  );
}
